/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ListACourtRouteImport } from './routes/list-a-court'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WhereRouteImport } from './routes/where'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCoachesRouteImport } from './routes/app/coaches'
import { Route as AppCourtsRouteImport } from './routes/app/courts'
import { Route as AppDeskRouteImport } from './routes/app/desk'
import { Route as AppLeaguesRouteImport } from './routes/app/leagues'
import { Route as AppMentalRouteImport } from './routes/app/mental'
import { Route as AppPartnersRouteImport } from './routes/app/partners'
import { Route as AppPlayRouteImport } from './routes/app/play'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppProgressRouteImport } from './routes/app/progress'
import { Route as AppYouRouteImport } from './routes/app/you'
import { Route as WhereIndexRouteImport } from './routes/where.index'
import { Route as WhereCityRouteImport } from './routes/where.$city'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppLeaguesIndexRouteImport } from './routes/app/leagues.index'
import { Route as AppLeaguesIdRouteImport } from './routes/app/leagues.$id'
import { Route as WhereCityIndexRouteImport } from './routes/where.$city.index'
import { Route as WhereCitySlugRouteImport } from './routes/where.$city.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ListACourtRoute = ListACourtRouteImport.update({
  id: '/list-a-court',
  path: '/list-a-court',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WhereRoute = WhereRouteImport.update({
  id: '/where',
  path: '/where',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachesRoute = AppCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => AppRoute,
} as any)
const AppCourtsRoute = AppCourtsRouteImport.update({
  id: '/courts',
  path: '/courts',
  getParentRoute: () => AppRoute,
} as any)
const AppDeskRoute = AppDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaguesRoute = AppLeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => AppRoute,
} as any)
const AppMentalRoute = AppMentalRouteImport.update({
  id: '/mental',
  path: '/mental',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersRoute = AppPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayRoute = AppPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppYouRoute = AppYouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => AppRoute,
} as any)
const WhereIndexRoute = WhereIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WhereRoute,
} as any)
const WhereCityRoute = WhereCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => WhereRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLeaguesIndexRoute = AppLeaguesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeaguesRoute,
} as any)
const AppLeaguesIdRoute = AppLeaguesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLeaguesRoute,
} as any)
const WhereCityIndexRoute = WhereCityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WhereCityRoute,
} as any)
const WhereCitySlugRoute = WhereCitySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WhereCityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/join': typeof JoinRoute
  '/list-a-court': typeof ListACourtRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/where': typeof WhereRouteWithChildren
  '/app/coaches': typeof AppCoachesRoute
  '/app/courts': typeof AppCourtsRoute
  '/app/desk': typeof AppDeskRoute
  '/app/leagues': typeof AppLeaguesRouteWithChildren
  '/app/mental': typeof AppMentalRoute
  '/app/partners': typeof AppPartnersRoute
  '/app/play': typeof AppPlayRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/you': typeof AppYouRoute
  '/where/$city': typeof WhereCityRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/where/': typeof WhereIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/leagues/$id': typeof AppLeaguesIdRoute
  '/where/$city/$slug': typeof WhereCitySlugRoute
  '/app/leagues/': typeof AppLeaguesIndexRoute
  '/where/$city/': typeof WhereCityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/list-a-court': typeof ListACourtRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/coaches': typeof AppCoachesRoute
  '/app/courts': typeof AppCourtsRoute
  '/app/desk': typeof AppDeskRoute
  '/app/mental': typeof AppMentalRoute
  '/app/partners': typeof AppPartnersRoute
  '/app/play': typeof AppPlayRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/you': typeof AppYouRoute
  '/app': typeof AppIndexRoute
  '/where': typeof WhereIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/leagues/$id': typeof AppLeaguesIdRoute
  '/where/$city/$slug': typeof WhereCitySlugRoute
  '/app/leagues': typeof AppLeaguesIndexRoute
  '/where/$city': typeof WhereCityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/join': typeof JoinRoute
  '/list-a-court': typeof ListACourtRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/where': typeof WhereRouteWithChildren
  '/app/coaches': typeof AppCoachesRoute
  '/app/courts': typeof AppCourtsRoute
  '/app/desk': typeof AppDeskRoute
  '/app/leagues': typeof AppLeaguesRouteWithChildren
  '/app/mental': typeof AppMentalRoute
  '/app/partners': typeof AppPartnersRoute
  '/app/play': typeof AppPlayRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/you': typeof AppYouRoute
  '/where/$city': typeof WhereCityRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/where/': typeof WhereIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/leagues/$id': typeof AppLeaguesIdRoute
  '/where/$city/$slug': typeof WhereCitySlugRoute
  '/app/leagues/': typeof AppLeaguesIndexRoute
  '/where/$city/': typeof WhereCityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/join'
    | '/list-a-court'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/where'
    | '/app/coaches'
    | '/app/courts'
    | '/app/desk'
    | '/app/leagues'
    | '/app/mental'
    | '/app/partners'
    | '/app/play'
    | '/app/profile'
    | '/app/progress'
    | '/app/you'
    | '/where/$city'
    | '/app/'
    | '/where/'
    | '/api/auth/$'
    | '/app/leagues/$id'
    | '/where/$city/$slug'
    | '/app/leagues/'
    | '/where/$city/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/list-a-court'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/app/coaches'
    | '/app/courts'
    | '/app/desk'
    | '/app/mental'
    | '/app/partners'
    | '/app/play'
    | '/app/profile'
    | '/app/progress'
    | '/app/you'
    | '/app'
    | '/where'
    | '/api/auth/$'
    | '/app/leagues/$id'
    | '/where/$city/$slug'
    | '/app/leagues'
    | '/where/$city'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/join'
    | '/list-a-court'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/where'
    | '/app/coaches'
    | '/app/courts'
    | '/app/desk'
    | '/app/leagues'
    | '/app/mental'
    | '/app/partners'
    | '/app/play'
    | '/app/profile'
    | '/app/progress'
    | '/app/you'
    | '/where/$city'
    | '/app/'
    | '/where/'
    | '/api/auth/$'
    | '/app/leagues/$id'
    | '/where/$city/$slug'
    | '/app/leagues/'
    | '/where/$city/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  JoinRoute: typeof JoinRoute
  ListACourtRoute: typeof ListACourtRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhereRoute: typeof WhereRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-a-court': {
      id: '/list-a-court'
      path: '/list-a-court'
      fullPath: '/list-a-court'
      preLoaderRoute: typeof ListACourtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/where': {
      id: '/where'
      path: '/where'
      fullPath: '/where'
      preLoaderRoute: typeof WhereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coaches': {
      id: '/app/coaches'
      path: '/coaches'
      fullPath: '/app/coaches'
      preLoaderRoute: typeof AppCoachesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courts': {
      id: '/app/courts'
      path: '/courts'
      fullPath: '/app/courts'
      preLoaderRoute: typeof AppCourtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/desk': {
      id: '/app/desk'
      path: '/desk'
      fullPath: '/app/desk'
      preLoaderRoute: typeof AppDeskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leagues': {
      id: '/app/leagues'
      path: '/leagues'
      fullPath: '/app/leagues'
      preLoaderRoute: typeof AppLeaguesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mental': {
      id: '/app/mental'
      path: '/mental'
      fullPath: '/app/mental'
      preLoaderRoute: typeof AppMentalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/partners': {
      id: '/app/partners'
      path: '/partners'
      fullPath: '/app/partners'
      preLoaderRoute: typeof AppPartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/play': {
      id: '/app/play'
      path: '/play'
      fullPath: '/app/play'
      preLoaderRoute: typeof AppPlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/you': {
      id: '/app/you'
      path: '/you'
      fullPath: '/app/you'
      preLoaderRoute: typeof AppYouRouteImport
      parentRoute: typeof AppRoute
    }
    '/where/': {
      id: '/where/'
      path: '/'
      fullPath: '/where/'
      preLoaderRoute: typeof WhereIndexRouteImport
      parentRoute: typeof WhereRoute
    }
    '/where/$city': {
      id: '/where/$city'
      path: '/$city'
      fullPath: '/where/$city'
      preLoaderRoute: typeof WhereCityRouteImport
      parentRoute: typeof WhereRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/leagues/': {
      id: '/app/leagues/'
      path: '/'
      fullPath: '/app/leagues/'
      preLoaderRoute: typeof AppLeaguesIndexRouteImport
      parentRoute: typeof AppLeaguesRoute
    }
    '/app/leagues/$id': {
      id: '/app/leagues/$id'
      path: '/$id'
      fullPath: '/app/leagues/$id'
      preLoaderRoute: typeof AppLeaguesIdRouteImport
      parentRoute: typeof AppLeaguesRoute
    }
    '/where/$city/': {
      id: '/where/$city/'
      path: '/'
      fullPath: '/where/$city/'
      preLoaderRoute: typeof WhereCityIndexRouteImport
      parentRoute: typeof WhereCityRoute
    }
    '/where/$city/$slug': {
      id: '/where/$city/$slug'
      path: '/$slug'
      fullPath: '/where/$city/$slug'
      preLoaderRoute: typeof WhereCitySlugRouteImport
      parentRoute: typeof WhereCityRoute
    }
  }
}

interface AppLeaguesRouteChildren {
  AppLeaguesIdRoute: typeof AppLeaguesIdRoute
  AppLeaguesIndexRoute: typeof AppLeaguesIndexRoute
}

const AppLeaguesRouteChildren: AppLeaguesRouteChildren = {
  AppLeaguesIdRoute: AppLeaguesIdRoute,
  AppLeaguesIndexRoute: AppLeaguesIndexRoute,
}

const AppLeaguesRouteWithChildren = AppLeaguesRoute._addFileChildren(
  AppLeaguesRouteChildren,
)

interface AppRouteChildren {
  AppCoachesRoute: typeof AppCoachesRoute
  AppCourtsRoute: typeof AppCourtsRoute
  AppDeskRoute: typeof AppDeskRoute
  AppLeaguesRoute: typeof AppLeaguesRouteWithChildren
  AppMentalRoute: typeof AppMentalRoute
  AppPartnersRoute: typeof AppPartnersRoute
  AppPlayRoute: typeof AppPlayRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppYouRoute: typeof AppYouRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoachesRoute: AppCoachesRoute,
  AppCourtsRoute: AppCourtsRoute,
  AppDeskRoute: AppDeskRoute,
  AppLeaguesRoute: AppLeaguesRouteWithChildren,
  AppMentalRoute: AppMentalRoute,
  AppPartnersRoute: AppPartnersRoute,
  AppPlayRoute: AppPlayRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppYouRoute: AppYouRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface WhereCityRouteChildren {
  WhereCitySlugRoute: typeof WhereCitySlugRoute
  WhereCityIndexRoute: typeof WhereCityIndexRoute
}

const WhereCityRouteChildren: WhereCityRouteChildren = {
  WhereCitySlugRoute: WhereCitySlugRoute,
  WhereCityIndexRoute: WhereCityIndexRoute,
}

const WhereCityRouteWithChildren = WhereCityRoute._addFileChildren(
  WhereCityRouteChildren,
)

interface WhereRouteChildren {
  WhereCityRoute: typeof WhereCityRouteWithChildren
  WhereIndexRoute: typeof WhereIndexRoute
}

const WhereRouteChildren: WhereRouteChildren = {
  WhereCityRoute: WhereCityRouteWithChildren,
  WhereIndexRoute: WhereIndexRoute,
}

const WhereRouteWithChildren = WhereRoute._addFileChildren(WhereRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  JoinRoute: JoinRoute,
  ListACourtRoute: ListACourtRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhereRoute: WhereRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
